# Generated by Django 3.2.7 on 2021-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('chassi', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=100)),
                ('nascimento', models.IntegerField()),
                ('endereco', models.CharField(max_length=250)),
                ('funcao', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=25)),
            ],
        ),
    ]
