# Generated by Django 3.2.7 on 2021-10-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vendedores_rua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='chassi',
        ),
    ]
