# Generated by Django 3.2.7 on 2021-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_carros_chassi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='nascimento',
            field=models.CharField(max_length=12),
        ),
    ]
