# Generated by Django 3.2.7 on 2021-10-06 16:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vendedores_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_image_carros),
        ),
    ]
