# Generated by Django 3.2.7 on 2021-10-13 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carros_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carros',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterModelTable(
            name='carros',
            table='app_carros',
        ),
    ]
