# Generated by Django 3.2.7 on 2021-10-14 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orcamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='data_orcamento',
            field=models.CharField(default=-1.0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='telefone_cliente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='validade_orcamento',
            field=models.CharField(default=datetime.datetime(2021, 10, 14, 18, 39, 10, 784583, tzinfo=utc), max_length=12),
            preserve_default=False,
        ),
    ]
