# Generated by Django 3.2.7 on 2021-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211014_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentos',
            name='telefone_cliente',
            field=models.CharField(max_length=12),
        ),
    ]
